In [ ]:
from bs4 import BeautifulSoup
import requests
import pandas as pd

url = r"https://en.wikipedia.org/wiki/List_of_comedy_anime"

website = requests.get(url)
raw_code = BeautifulSoup(website.text, 'html')
print(raw_code)

In [2]:
main_data = raw_code.find("table", class_ = "wikitable sortable")
# location of the table: <table class="wikitable sortable jquery-tablesorter" border="1">

In [3]:
# Get the main titles of the desired table 
raw_titles = main_data.find_all('th')
titles = [title.text.strip() for title in raw_titles]
titles

['Title', 'Type', 'Year(s)', 'Director', 'Studio', 'Ref']

In [4]:
# Create the data frame
main_table = pd.DataFrame(columns = titles)
main_table

Empty DataFrame
Columns: [Title, Type, Year(s), Director, Studio, Ref]
Index: []

In [6]:
raw_rows = main_data.find_all('tr')
for row in raw_rows[1:]:
    row_data = row.find_all('td')
    clean_row_data = [clean_row.text.strip() for clean_row in row_data]
    df_length = len(main_table)
    # Here, I found that, for some reason, the rows  that had no value in the column Ref sometimes are not registered as '' like normal
    # and does not have data at all in that space, this code here fixed it
    if len(clean_row_data) < len(titles):
        clean_row_data.append('')
    main_table.loc[df_length] = clean_row_data
main_table

,Title,Type,Year(s),Director,Studio,Ref
0,Urusei Yatsura (1981),TV series,1981,"Mamoru Oshii, Kazuo Yamazaki","Studio Pierrot, Studio Deen",[1][2]
1,Tonde Mon Pe,TV series,1982,Shigetsugu Yoshida,TMS Entertainment,
2,Ranma ½,TV series,1989,"Tomomi Mochizuki, Tsutomu Shibayama",Studio Deen,[2]
3,Ranma ½ Nettōhen,TV series,1989,"Koji Sawai, Junji Nishimura",Studio Deen,[2]
4,Gosenzo-sama Banbanzai!,OVA series,1989,Mamoru Oshii,Pierrot,[3]
...,...,...,...,...,...,...
92,Spy × Family,TV series,2022,Kazuhiro Fukuhashi,"Wit Studio, CloverWorks",
93,Bocchi the Rock!,TV series,2022,Keiichirō Saitō,CloverWorks,
94,Chainsaw Man,TV series,2022,Ryū Nakayama,MAPPA,
95,Urusei Yatsura (2022),TV series,2022,"Hideya Takahashi, Yasuhiro Kimura, Takahiro Kamei",David Production,
96,KonoSuba:An Explosion on This Wonderful World!,TV series,2023,"Takaomi Kanasaki, Yujiro Abe",Drive,